export const dataPlans = [
  // ------------------ MTN ------------------
  {
    db_id: 2,
    network: "mtn",
    network_code: 1, // numeric code for MTN
    plan_id: 5,
    plan_type: "Data share",
    data: "1 GB",
    price: 599.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 3,
    network: "mtn",
    network_code: 1,
    plan_id: 315,
    plan_type: "Data share",
    data: "1 GB",
    price: 549.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 4,
    network: "mtn",
    network_code: 1,
    plan_id: 316,
    plan_type: "Data share",
    data: "2 GB",
    price: 1340.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 5,
    network: "mtn",
    network_code: 1,
    plan_id: 317,
    plan_type: "Data share",
    data: "3 GB",
    price: 2010.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 7,
    network: "mtn",
    network_code: 1,
    plan_id: 653,
    plan_type: "Data share",
    data: "5 GB",
    price: 3250.0,
    validity: "Monthly",
    active: true,
  },

  // MTN Gifting

  // ------------------ MTN GIFTING Plans ------------------

  {
    db_id: 56,
    network: "mtn",
    network_code: 1,
    plan_id: 619,
    plan_type: "GIFTING",
    data: "500 MB",
    price: 495.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 44,
    network: "mtn",
    network_code: 1,
    plan_id: 540,
    plan_type: "GIFTING",
    data: "750 MB",
    price: 446.0,
    validity: "3 days",
    active: true,
  },
  {
    db_id: 51,
    network: "mtn",
    network_code: 1,
    plan_id: 601,
    plan_type: "GIFTING",
    data: "1 GB",
    price: 495.0,
    validity: "1 day (+1.5 mins)",
    active: true,
  },
  {
    db_id: 57,
    network: "mtn",
    network_code: 1,
    plan_id: 620,
    plan_type: "GIFTING",
    data: "1 GB",
    price: 792.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 58,
    network: "mtn",
    network_code: 1,
    plan_id: 622,
    plan_type: "GIFTING",
    data: "1.5 GB",
    price: 990.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 52,
    network: "mtn",
    network_code: 1,
    plan_id: 604,
    plan_type: "GIFTING",
    data: "2 GB",
    price: 743.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 55,
    network: "mtn",
    network_code: 1,
    plan_id: 612,
    plan_type: "GIFTING",
    data: "2 GB",
    price: 1490.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 59,
    network: "mtn",
    network_code: 1,
    plan_id: 623,
    plan_type: "GIFTING",
    data: "2.7 GB",
    price: 1920.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 50,
    network: "mtn",
    network_code: 1,
    plan_id: 555,
    plan_type: "GIFTING",
    data: "2.5 GB",
    price: 891.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 63,
    network: "mtn",
    network_code: 1,
    plan_id: 660,
    plan_type: "GIFTING",
    data: "3.2 GB",
    price: 990.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 66,
    network: "mtn",
    network_code: 1,
    plan_id: 680,
    plan_type: "GIFTING",
    data: "3.5 GB",
    price: 1000.0,
    validity: "1 day",
    active: true,
  },
  {
    db_id: 65,
    network: "mtn",
    network_code: 1,
    plan_id: 679,
    plan_type: "GIFTING",
    data: "4 GB",
    price: 1200.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 64,
    network: "mtn",
    network_code: 1,
    plan_id: 678,
    plan_type: "GIFTING",
    data: "5.5 GB",
    price: 1500.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 54,
    network: "mtn",
    network_code: 1,
    plan_id: 609,
    plan_type: "GIFTING",
    data: "6 GB",
    price: 2475.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 60,
    network: "mtn",
    network_code: 1,
    plan_id: 645,
    plan_type: "GIFTING",
    data: "11 GB",
    price: 3465.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 53,
    network: "mtn",
    network_code: 1,
    plan_id: 607,
    plan_type: "GIFTING",
    data: "16.5 GB",
    price: 6435.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 67,
    network: "mtn",
    network_code: 1,
    plan_id: 681,
    plan_type: "GIFTING",
    data: "34 GB",
    price: 10000.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 45,
    network: "mtn",
    network_code: 1,
    plan_id: 541,
    plan_type: "GIFTING",
    data: "20 GB",
    price: 7425.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 46,
    network: "mtn",
    network_code: 1,
    plan_id: 542,
    plan_type: "GIFTING",
    data: "25 GB",
    price: 8910.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 47,
    network: "mtn",
    network_code: 1,
    plan_id: 544,
    plan_type: "GIFTING",
    data: "75 GB",
    price: 19800.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 48,
    network: "mtn",
    network_code: 1,
    plan_id: 545,
    plan_type: "GIFTING",
    data: "150 GB",
    price: 34650.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 49,
    network: "mtn",
    network_code: 1,
    plan_id: 546,
    plan_type: "GIFTING",
    data: "250 GB",
    price: 54450.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 62,
    network: "mtn",
    network_code: 1,
    plan_id: 650,
    plan_type: "GIFTING",
    data: "800 GB",
    price: 123750.0,
    validity: "1 year",
    active: true,
  },

  // MTN Awoof
  {
    db_id: 68,
    network: "mtn",
    network_code: 1,
    plan_id: 564,
    plan_type: "MTN AWOOF",
    data: "11 GB",
    price: 3599.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 69,
    network: "mtn",
    network_code: 1,
    plan_id: 616,
    plan_type: "MTN AWOOF",
    data: "1 GB",
    price: 549.0,
    validity: "1 day",
    active: true,
  },
  {
    db_id: 70,
    network: "mtn",
    network_code: 1,
    plan_id: 618,
    plan_type: "MTN AWOOF",
    data: "6 GB",
    price: 2579.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 71,
    network: "mtn",
    network_code: 1,
    plan_id: 624,
    plan_type: "MTN AWOOF",
    data: "14.5 GB",
    price: 5099.0,
    validity: "30 days",
    active: true,
  },

  // ------------------ Airtel ------------------
  {
    db_id: 107,
    network: "airtel",
    network_code: 2, // numeric code for Airtel
    plan_id: 164,
    plan_type: "GIFTING",
    data: "200 MB",
    price: 198.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 108,
    network: "airtel",
    network_code: 2,
    plan_id: 326,
    plan_type: "GIFTING",
    data: "2 GB",
    price: 594.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 109,
    network: "airtel",
    network_code: 2,
    plan_id: 577,
    plan_type: "GIFTING",
    data: "6 GB",
    price: 2475.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 110,
    network: "airtel",
    network_code: 2,
    plan_id: 579,
    plan_type: "GIFTING",
    data: "300 MB",
    price: 297.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 111,
    network: "airtel",
    network_code: 2,
    plan_id: 580,
    plan_type: "GIFTING",
    data: "3 GB",
    price: 1980.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 112,
    network: "airtel",
    network_code: 2,
    plan_id: 581,
    plan_type: "GIFTING",
    data: "8 GB",
    price: 2970.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 113,
    network: "airtel",
    network_code: 2,
    plan_id: 583,
    plan_type: "GIFTING",
    data: "13 GB",
    price: 4950.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 114,
    network: "airtel",
    network_code: 2,
    plan_id: 585,
    plan_type: "GIFTING",
    data: "60 GB",
    price: 14850.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 115,
    network: "airtel",
    network_code: 2,
    plan_id: 588,
    plan_type: "GIFTING",
    data: "35 GB",
    price: 9990.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 116,
    network: "airtel",
    network_code: 2,
    plan_id: 632,
    plan_type: "GIFTING",
    data: "18 GB",
    price: 4850.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 117,
    network: "airtel",
    network_code: 2,
    plan_id: 633,
    plan_type: "GIFTING",
    data: "2 GB",
    price: 1485.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 118,
    network: "airtel",
    network_code: 2,
    plan_id: 634,
    plan_type: "GIFTING",
    data: "4 GB",
    price: 2475.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 119,
    network: "airtel",
    network_code: 2,
    plan_id: 644,
    plan_type: "GIFTING",
    data: "1 GB",
    price: 792.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 120,
    network: "airtel",
    network_code: 2,
    plan_id: 648,
    plan_type: "GIFTING",
    data: "1.5 GB",
    price: 990.0,
    validity: "7 days",
    active: true,
  },
  {
    db_id: 121,
    network: "airtel",
    network_code: 2,
    plan_id: 651,
    plan_type: "GIFTING",
    data: "100 GB",
    price: 19800.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 122,
    network: "airtel",
    network_code: 2,
    plan_id: 661,
    plan_type: "GIFTING",
    data: "75 MB",
    price: 74.25,
    validity: "1 day",
    active: true,
  },
  {
    db_id: 123,
    network: "airtel",
    network_code: 2,
    plan_id: 662,
    plan_type: "GIFTING",
    data: "100 MB",
    price: 99.0,
    validity: "Daily",
    active: true,
  },
  {
    db_id: 124,
    network: "airtel",
    network_code: 2,
    plan_id: 663,
    plan_type: "GIFTING",
    data: "3.2 GB",
    price: 990.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 125,
    network: "airtel",
    network_code: 2,
    plan_id: 664,
    plan_type: "GIFTING",
    data: "5 GB",
    price: 1485.0,
    validity: "2 days",
    active: true,
  },
  {
    db_id: 126,
    network: "airtel",
    network_code: 2,
    plan_id: 665,
    plan_type: "GIFTING",
    data: "10 GB",
    price: 3960.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 127,
    network: "airtel",
    network_code: 2,
    plan_id: 666,
    plan_type: "GIFTING",
    data: "25 GB",
    price: 7920.0,
    validity: "30 days",
    active: true,
  },
  {
    db_id: 128,
    network: "airtel",
    network_code: 2,
    plan_id: 667,
    plan_type: "GIFTING",
    data: "160 GB",
    price: 29700.0,
    validity: "Monthly",
    active: true,
  },
  {
    db_id: 129,
    network: "airtel",
    network_code: 2,
    plan_id: 668,
    plan_type: "GIFTING",
    data: "300 GB",
    price: 49500.0,
    validity: "90 days",
    active: true,
  },
  {
    db_id: 130,
    network: "airtel",
    network_code: 2,
    plan_id: 669,
    plan_type: "GIFTING",
    data: "350 GB",
    price: 59400.0,
    validity: "Monthly",
    active: true,
  },

  // ... add remaining Airtel plans here
];
